# -*- coding: utf-8 -*-
"""14일차_220519.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhPJUvjTYeHY4p6UZ2EUBN6EAaN6xl8y
"""

# 325page)

import requests
from bs4 import BeautifulSoup

url = 'https://movie.naver.com/movie/bi/mi/basic.naver'
param = {'code':10016}
response = requests.get(url, params=param)
html = response.text
soup = BeautifulSoup(html, 'html.parser')

review_list = soup.find_all('div', class_='score_reple')
#print(review_list)

for review in review_list:
  print(review.find('p').text.strip()) # 공백을 제외한 p태그에 해당하는 내용을 가져온다.

# 섹션 18 응용예제 1)

import requests
from bs4 import BeautifulSoup

url = 'https://movie.naver.com/movie/sdb/rank/rpeople.naver'
response = requests.get(url)
html = response.text
soup = BeautifulSoup(html, 'html.parser')

result_list = soup.find_all('td', class_='title')
print(result_list)

movie_in = []
for result in result_list:
  movie_in.append(result.text.strip())

print(movie_in)

for person in movie_in:
  print(person)

# 섹션 18 응용예제 2)

import requests
from bs4 import BeautifulSoup

url = 'https://movie.naver.com/movie/sdb/rank/rmovie.naver'
response = requests.get(url)
html = response.text
soup = BeautifulSoup(html, 'html.parser')

movie_list = soup.find_all('div', class_='tit3')

print(movie_list)

for idx, movie in enumerate(movie_list):
  print('{}위 : {}'.format(idx+1, movie.text.strip()))

### 데이터 시각화 ###

# 꺾은선형 그래프 : plot()

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
x = [0, 1, 2, 3, 4]   # x축 값
y = [4, 1, 3, 5, 2]   # y축 값
axes.plot(x, y)
plt.show()

# 꺾은선형 그래프 2개

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
x1 = [0, 1, 2, 3, 4]   # x1 축값
y1 = [4, 1, 3, 5, 2]   # y1 축값
x2 = [0, 1, 2, 3, 4]   # x2
y2 = [0, 8, 5, 3, 1]   # y2
axes.plot(x1, y1)
axes.plot(x2, y2)
plt.show()

# 꺾은선형 선 꾸미기

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
axes.plot([0, 1, 2, 3, 4], [0, 3, 0, 3, 0], linestyle='dotted', linewidth=5.0)  # 점선, 선 굵기
axes.plot([0, 1, 2, 3, 4], [1, 2, 3, 4, 5], color='r', marker='v') # 선 색 빨강, 표식 추가
plt.show()

# 340page)

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
x = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
y = [1200, 800, 500, 400, 700, 800]
axes.plot(x, y, linestyle='--', marker='^')
plt.show()

# 막대그래프 : bar()

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
x = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
y = [8, 6, 5, 4, 7, 9, 5]
axes.bar(x, y)
plt.title('weekday call')   # 차트 제목
plt.xlabel('week')          # x축 제목
plt.ylabel('call')          # y축 제목
plt.show()

# 산포그래프 : scatter()

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
x = [1, 2, 3, 4, 5, 6]
y = [6, 4, 1, 2, 7, 5]
area = [50, 100, 150, 200, 250, 300]  # 각 점의 크기
color = ['red', 'green', 'blue', 'orange', 'aqua', 'crimson']  # 각 점의 색상
axes.scatter(x, y, s=area, c=color)  # 점 크기와 색상 설정
plt.show()

# 343page)

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
noise = [20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
stress = [10, 11, 15, 20, 30, 42, 55, 70, 88, 110, 150]
axes.scatter(noise, stress, s=50)  # 각 점의 크기를 50으로
plt.xlabel('noise')   # x축 제목
plt.ylabel('stress')  # y축 제목
plt.show()

# 원형그래프 : pie()

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
data = [1, 2, 3]
axes.pie(data)
plt.axis('equal')   # 일반 원형
plt.show()

# 범례와 레이블을 추가한 원형그래프

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
data = [1, 2, 3]
label = ['Good', 'Bad', 'Normal']
axes.pie(data, labels=label, autopct='%d%%')  # 레이블 포함, 정수 %로 표시
plt.axis('equal')
plt.legend(label, loc='center left')  # 범례
plt.show()

# 섹션 19 응용예제 1)

import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
data = [0.18, 0.3, 3.33, 3.75, 0.38, 25, 0.25, 2.75, 0.1]
vitamin = ['vitamin A', 'vitamin B1', 'vitamin B2', 'Niacin', 'vitamin B6',
           'vitamin C', 'vitamin D', 'vitamin E', 'folate']
axes.pie(data, labels=vitamin, autopct='%0.1f%%')
plt.axis('equal')
plt.show()

# 응용예제 2)
import random
import matplotlib.pyplot as plt

figure = plt.figure()
axes = figure.add_subplot(111)  # 1행 1열 첫번째
x = [n for n in range(101)]
y1 = []   # 꺾은선
y2 = []   # 막대
for i in range(101):
  y1.append(random.randint(0, 100))
  y2.append(random.randint(0, 100))
axes.plot(x, y1, color='r', marker='.')
axes.bar(x, y2, color='g')
plt.show()

